### ISSUE TITLE
Build fails on test: querySensors FAILED

### ISSUE THREAD

**Issue by oori** [cansik/librealsense-java#2]
```
org.intel.rs.test.SensorTest > querySensors FAILED
    java.lang.NullPointerException at SensorTest.java:29

9 tests completed, 1 failed
```

It will build successfully once I comment out the following line:
https://github.com/cansik/librealsense-java/blob/7f6dc29fcf8aadba8183d0d50c0c8229163a2865/src/test/java/org/intel/rs/test/SensorTest.java#L29

**Comment by cansik** [comment]
Thanks, I will have a look at that. Have you tested it with a device connected or without?

**Comment by cansik** [comment]
Should be fixed now, thx for report.
